#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pydocstyle
Version  : 6.1.1
Release  : 43
URL      : https://files.pythonhosted.org/packages/4c/30/4cdea3c8342ad343d41603afc1372167c224a04dc5dc0bf4193ccb39b370/pydocstyle-6.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/4c/30/4cdea3c8342ad343d41603afc1372167c224a04dc5dc0bf4193ccb39b370/pydocstyle-6.1.1.tar.gz
Summary  : Python docstring style checker
Group    : Development/Tools
License  : MIT
Requires: pypi-pydocstyle-bin = %{version}-%{release}
Requires: pypi-pydocstyle-license = %{version}-%{release}
Requires: pypi-pydocstyle-python = %{version}-%{release}
Requires: pypi-pydocstyle-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(snowballstemmer)

%description
====================================

%package bin
Summary: bin components for the pypi-pydocstyle package.
Group: Binaries
Requires: pypi-pydocstyle-license = %{version}-%{release}

%description bin
bin components for the pypi-pydocstyle package.


%package license
Summary: license components for the pypi-pydocstyle package.
Group: Default

%description license
license components for the pypi-pydocstyle package.


%package python
Summary: python components for the pypi-pydocstyle package.
Group: Default
Requires: pypi-pydocstyle-python3 = %{version}-%{release}

%description python
python components for the pypi-pydocstyle package.


%package python3
Summary: python3 components for the pypi-pydocstyle package.
Group: Default
Requires: python3-core
Provides: pypi(pydocstyle)
Requires: pypi(snowballstemmer)

%description python3
python3 components for the pypi-pydocstyle package.


%prep
%setup -q -n pydocstyle-6.1.1
cd %{_builddir}/pydocstyle-6.1.1
pushd ..
cp -a pydocstyle-6.1.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656397579
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pydocstyle
cp %{_builddir}/pydocstyle-6.1.1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydocstyle/8c47a6512d3c70bf08a9218a76c52dd36f5851ce
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pydocstyle

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pydocstyle/8c47a6512d3c70bf08a9218a76c52dd36f5851ce

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
